"""Insights synthesis — the brain reflecting on its own history.

Read-only. Aggregates persisted decision history and the cost record into a
single forward-looking briefing: deterministic observations about the past,
run-rate predictions about the near future, and improvement recommendations
mined from operator behaviour. Nothing here is generated by a model and
nothing is applied automatically — every recommendation is a suggestion for
a human (the learning loop stays HITL-sacred).
"""

import json
import sqlite3
import statistics

from fastapi import APIRouter, Depends
from pydantic import BaseModel

from app import db
from app.detection import load_daily_costs
from app.reflex import suggest_reflex_rules

router = APIRouter(prefix="/insights", tags=["insights"])

_TREND_WINDOW = 7  # days per comparison bucket for the week-over-week run rate


class InsightPrediction(BaseModel):
    horizon: str
    statement: str
    basis: str


class InsightRecommendation(BaseModel):
    focus: str
    action: str
    evidence: str


class InsightsReport(BaseModel):
    decisions_considered: int
    cost_days: int
    observations: list[str]
    predictions: list[InsightPrediction]
    recommendations: list[InsightRecommendation]
    note: str


def _daily_totals(records: list) -> list[float]:
    by_date: dict[str, float] = {}
    for record in records:
        key = str(record["date"])
        by_date[key] = by_date.get(key, 0.0) + float(record["cost"])
    return [by_date[key] for key in sorted(by_date)]


@router.get("")
def insights(conn: sqlite3.Connection = Depends(db.get_db)) -> InsightsReport:
    """Reflect on persisted history and advise — deterministic, HITL-safe."""
    observations: list[str] = []
    predictions: list[InsightPrediction] = []
    recommendations: list[InsightRecommendation] = []

    # --- decision history ---------------------------------------------------
    row = conn.execute(
        "SELECT COUNT(*) AS total, "
        "SUM(CASE WHEN verdict = 'approved' THEN 1 ELSE 0 END) AS approved, "
        "SUM(CASE WHEN verdict = 'rejected' THEN 1 ELSE 0 END) AS rejected "
        "FROM decisions"
    ).fetchone()
    total = row["total"] or 0
    approved = row["approved"] or 0
    rejected = row["rejected"] or 0
    if total:
        rate = round(100 * approved / total, 1)
        observations.append(
            f"{total} operator decisions on record — {approved} approved, "
            f"{rejected} rejected ({rate}% approval rate)."
        )
    else:
        observations.append("No operator decisions on record yet.")

    # Conservative approved-savings roll-up straight from the action detail.
    approved_rows = conn.execute(
        "SELECT detail_json FROM actions WHERE state IN ('approved', 'executed')"
    ).fetchall()
    approved_savings = 0.0
    for detail_row in approved_rows:
        try:
            detail = json.loads(detail_row["detail_json"]) or {}
            savings = detail.get("savings") or {}
            approved_savings += float(savings.get("cautious_monthly", 0.0) or 0.0)
        except (json.JSONDecodeError, TypeError, ValueError):
            continue
    if approved_savings > 0:
        observations.append(
            f"Approved actions project ${approved_savings:.2f}/month in "
            "conservative savings (computed, never generated)."
        )

    # --- cost run-rate + projection ----------------------------------------
    totals = _daily_totals(load_daily_costs())
    cost_days = len(totals)
    if cost_days >= _TREND_WINDOW:
        last = statistics.mean(totals[-_TREND_WINDOW:])
        predictions.append(
            InsightPrediction(
                horizon="next 30 days",
                statement=f"projected spend ≈ ${last * 30:.2f}",
                basis=f"last-{_TREND_WINDOW}-day daily mean (${last:.2f}) × 30",
            )
        )
        if cost_days >= 2 * _TREND_WINDOW:
            prior = statistics.mean(totals[-2 * _TREND_WINDOW : -_TREND_WINDOW])
            if prior > 0:
                pct = round(100 * (last - prior) / prior, 1)
                direction = "up" if pct > 0 else "down" if pct < 0 else "flat"
                observations.append(
                    f"Daily spend is trending {direction} {abs(pct)}% week over "
                    f"week (${prior:.2f}/day → ${last:.2f}/day)."
                )

    # --- improvement recommendations mined from behaviour ------------------
    for suggestion in suggest_reflex_rules(conn):
        recommendations.append(
            InsightRecommendation(
                focus=suggestion["service"],
                action="Adopt a pre-approved reflex playbook for this pattern.",
                evidence=(
                    f"{suggestion['approvals']} approvals, 0 rejections in "
                    f"{suggestion['window_days']} days."
                ),
            )
        )
    rejected_rows = conn.execute(
        "SELECT service, COUNT(*) AS rejections FROM decisions "
        "WHERE verdict = 'rejected' GROUP BY service "
        "HAVING rejections > 0 ORDER BY rejections DESC, service"
    ).fetchall()
    for reject_row in rejected_rows:
        recommendations.append(
            InsightRecommendation(
                focus=reject_row["service"],
                action="Review this service's detection threshold or option quality.",
                evidence=f"{reject_row['rejections']} operator rejections recorded.",
            )
        )

    return InsightsReport(
        decisions_considered=total,
        cost_days=cost_days,
        observations=observations,
        predictions=predictions,
        recommendations=recommendations,
        note=(
            "Deterministic synthesis over persisted history — figures are "
            "computed, not generated, and every recommendation is a suggestion "
            "for a human (nothing is applied automatically)."
        ),
    )
