"""Insights synthesis — the brain reflecting on its own history.

Read-only. Aggregates persisted decision history and the cost record into a
single forward-looking briefing: deterministic observations about the past,
run-rate predictions about the near future, and improvement recommendations
mined from operator behaviour. Nothing here is generated by a model and
nothing is applied automatically — every recommendation is a suggestion for
a human (the learning loop stays HITL-sacred).

What the room draws on, all of it recomputed per request from rows the
pipeline persisted: the decision record itself, the cost series, what alert
suppression folded away before a human saw it, the decision-quality figures
(latency, acceptance by severity, recurrence, the uncertainty the agents
named themselves), the runbook corpus's own hit rate, the reflex rules the
system has drafted from settled signatures — and the audit chain's verdict
on whether any of that record can still be trusted.

Two rules bind every line below and they matter more than the reading they
produce:

1. Nothing is generated. Every number traces to a query in this file or to
   a report module whose figures are themselves computed.
2. Nothing is asserted over a handful of rows. Each read carries an evidence
   bar; a read that has not cleared it is named in ``evidence_gaps`` and in
   a closing observation instead of being stated. A percentage over three
   decisions reads exactly like a percentage over three hundred, so the
   brain says which one it has.

Correlation is reported as correlation throughout: the room says what the
record contains and what a flat extrapolation of it implies, never why it
happened.
"""

import json
import sqlite3
import statistics
from datetime import date

from fastapi import APIRouter, Depends
from pydantic import BaseModel

from app import bus, db, history, ledger
from app.actions import suppressed_count
from app.analytics import decision_quality
from app.detection import load_daily_costs
from app.reflex import propose_reflex_rules, suggest_reflex_rules
from app.runbooks import effectiveness as runbook_effectiveness

router = APIRouter(prefix="/insights", tags=["insights"])

_TREND_WINDOW = 7  # days per comparison bucket for the week-over-week run rate

# --- evidence bars ---------------------------------------------------------
#
# The thresholds a read must clear before it is stated as a finding. They are
# deliberately modest — this is a demo corpus, not a fleet — but they are
# enforced, and every one of them has a test for the path where it is NOT met.

# Rates and latencies over the decision record.
_MIN_DECISIONS = 5
# Uncertainty codes tallied across the persisted agent traces.
_MIN_UNCERTAINTY_FLAGS = 5
# Distinct days a service must have been flagged before "it keeps coming
# back" is a pattern rather than a coincidence.
_MIN_RECURRENCE_DAYS = 3
# ...and the span that pattern must cover before a rate may be extrapolated
# from it. Three flags inside one week is not a per-fortnight rate.
_MIN_RECURRENCE_SPAN_DAYS = 14
_RECURRENCE_HORIZON_DAYS = 14


class InsightPrediction(BaseModel):
    horizon: str
    statement: str
    basis: str


class InsightRecommendation(BaseModel):
    focus: str
    action: str
    evidence: str


class InsightsReport(BaseModel):
    decisions_considered: int
    cost_days: int
    observations: list[str]
    predictions: list[InsightPrediction]
    recommendations: list[InsightRecommendation]
    # The reads that exist but have not earned a sentence yet, each with the
    # count it is short by. Published rather than silently skipped: "we have
    # not measured this" is itself a finding about a young system.
    evidence_gaps: list[str]
    note: str


def _daily_totals(records: list) -> list[float]:
    by_date: dict[str, float] = {}
    for record in records:
        key = str(record["date"])
        by_date[key] = by_date.get(key, 0.0) + float(record["cost"])
    return [by_date[key] for key in sorted(by_date)]


def _pct(part: int, whole: int) -> float:
    return round(100 * part / whole, 1)


def _suppression_fold(conn: sqlite3.Connection) -> tuple[int, int, int]:
    """(repeats folded, cards that absorbed them, services involved).

    Read off the same ``detail_json.suppression`` block the card renders, so
    the figure the brain quotes and the figure the inbox shows are the same
    number read from the same place.
    """
    repeats = 0
    cards = 0
    services: set[str] = set()
    for row in conn.execute(
        "SELECT a.detail_json AS detail_json, e.service AS service "
        "FROM actions a LEFT JOIN events e ON e.id = a.event_id"
    ):
        try:
            detail = json.loads(row["detail_json"])
        except (json.JSONDecodeError, TypeError):
            continue
        if not isinstance(detail, dict):
            continue
        folded = suppressed_count(detail)
        if folded <= 0:
            continue
        repeats += folded
        cards += 1
        if row["service"]:
            services.add(row["service"])
    return repeats, cards, len(services)


def _span_days(first: str, last: str) -> int | None:
    """Inclusive day span between two ISO dates, or None if unparseable."""
    try:
        return (date.fromisoformat(last) - date.fromisoformat(first)).days + 1
    except (TypeError, ValueError):
        return None


@router.get("")
def insights(conn: sqlite3.Connection = Depends(db.get_db)) -> InsightsReport:
    """Reflect on persisted history and advise — deterministic, HITL-safe."""
    return compute_insights(conn)


def compute_insights(conn: sqlite3.Connection) -> InsightsReport:
    """History synthesis, callable by the route, routines and self-review."""
    observations: list[str] = []
    predictions: list[InsightPrediction] = []
    recommendations: list[InsightRecommendation] = []
    gaps: list[str] = []

    # --- decision history ---------------------------------------------------
    row = conn.execute(
        "SELECT COUNT(*) AS total, "
        "SUM(CASE WHEN verdict = 'approved' THEN 1 ELSE 0 END) AS approved, "
        "SUM(CASE WHEN verdict = 'rejected' THEN 1 ELSE 0 END) AS rejected "
        "FROM decisions"
    ).fetchone()
    total = row["total"] or 0
    approved = row["approved"] or 0
    rejected = row["rejected"] or 0
    if total:
        rate = round(100 * approved / total, 1)
        observations.append(
            f"{total} operator decisions on record — {approved} approved, "
            f"{rejected} rejected ({rate}% approval rate)."
        )
    else:
        observations.append("No operator decisions on record yet.")

    # Conservative approved-savings roll-up straight from the action detail.
    approved_rows = conn.execute(
        "SELECT detail_json FROM actions WHERE state IN ('approved', 'executed')"
    ).fetchall()
    approved_savings = 0.0
    for detail_row in approved_rows:
        try:
            detail = json.loads(detail_row["detail_json"]) or {}
            savings = detail.get("savings") or {}
            approved_savings += float(savings.get("cautious_monthly", 0.0) or 0.0)
        except (json.JSONDecodeError, TypeError, ValueError):
            continue
    if approved_savings > 0:
        observations.append(
            f"Approved actions project ${approved_savings:.2f}/month in "
            "conservative savings (computed, never generated)."
        )

    # --- cost run-rate + projection ----------------------------------------
    totals = _daily_totals(load_daily_costs())
    cost_days = len(totals)
    if cost_days >= _TREND_WINDOW:
        last = statistics.mean(totals[-_TREND_WINDOW:])
        predictions.append(
            InsightPrediction(
                horizon="next 30 days",
                statement=f"projected spend ≈ ${last * 30:.2f}",
                basis=f"last-{_TREND_WINDOW}-day daily mean (${last:.2f}) × 30",
            )
        )
        if cost_days >= 2 * _TREND_WINDOW:
            prior = statistics.mean(totals[-2 * _TREND_WINDOW : -_TREND_WINDOW])
            if prior > 0:
                pct = round(100 * (last - prior) / prior, 1)
                direction = "up" if pct > 0 else "down" if pct < 0 else "flat"
                observations.append(
                    f"Daily spend is trending {direction} {abs(pct)}% week over "
                    f"week (${prior:.2f}/day → ${last:.2f}/day)."
                )

    # --- what suppression absorbed before a human ever saw it --------------
    # Arithmetic only: each folded repeat is one card that would otherwise
    # have been filed, because a repeat folds INTO an open card instead of
    # opening its own. No claim about what the operator would have done
    # with those cards — only how many never reached them.
    repeats, folding_cards, folding_services = _suppression_fold(conn)
    if repeats:
        observations.append(
            f"Alert suppression folded {repeats} repeat signal(s) into "
            f"{folding_cards} already-open card(s) across {folding_services} "
            f"service(s) — {folding_cards + repeats} cards' worth of signal "
            f"reached the inbox as {folding_cards}."
        )
    else:
        gaps.append("repeat-noise folding (no repeat signal has been folded yet)")

    # --- decision quality: how the desk itself is performing ----------------
    # One computed report, reused for four separate reads below rather than
    # recomputed per read.
    quality = decision_quality(conn)
    median_hours = quality.median_time_to_decision_hours
    mean_hours = quality.mean_time_to_decision_hours

    # The bar is the number of MEASURED intervals, not the number of
    # decisions: a seeded verdict carries no action and therefore no
    # filed→verdict pair, so counting it would let a median rest on a
    # sample smaller than the sentence claims.
    decided_ids = [
        row["id"]
        for row in conn.execute("SELECT id FROM actions WHERE decided_at IS NOT NULL")
    ]
    measured = len(history.deliberation_hours(conn, decided_ids))
    if measured >= _MIN_DECISIONS and median_hours is not None and mean_hours is not None:
        observations.append(
            f"Half of the {measured} measured deliberations ended within "
            f"{median_hours:.2f}h of filing (mean {mean_hours:.2f}h), timed on "
            "the append-only trail rather than from the card's own field."
        )
    else:
        gaps.append(
            f"time to decision ({measured} of {_MIN_DECISIONS} cards with a "
            "measured filed→verdict interval)"
        )

    # Acceptance sliced by the detector's own severity label. Only the
    # best-covered slice is quoted, and only if that slice alone clears the
    # bar — an aggregate rate hides exactly the disagreement worth seeing.
    severity_rows = [
        row
        for row in quality.acceptance
        if row.dimension == "severity" and row.acceptance_rate is not None
    ]
    covered = [row for row in severity_rows if row.decided >= _MIN_DECISIONS]
    if covered:
        widest = max(covered, key=lambda row: row.decided)
        observations.append(
            f"On '{widest.key}' severity the operators approved "
            f"{widest.approved} of {widest.decided} cards "
            f"({_pct(widest.approved, widest.decided)}%) — the best-covered "
            "severity slice on record."
        )
    else:
        best_covered = max((row.decided for row in severity_rows), default=0)
        gaps.append(
            f"acceptance by severity (best-covered severity has "
            f"{best_covered} of {_MIN_DECISIONS} decided cards)"
        )

    # What the agents said they were unsure ABOUT — tallied from the persisted
    # traces, so it covers every seat that spoke, not just the headline.
    flags = sum(source.occurrences for source in quality.top_uncertainty_sources)
    if flags >= _MIN_UNCERTAINTY_FLAGS:
        loudest = quality.top_uncertainty_sources[0]
        observations.append(
            f"When the agents flagged their own uncertainty they named "
            f"“{loudest.label}” most often — {loudest.occurrences} of {flags} "
            f"flags across {len(quality.top_uncertainty_sources)} distinct "
            "source(s) in the traces."
        )
    else:
        gaps.append(
            f"agent uncertainty sources ({flags} of {_MIN_UNCERTAINTY_FLAGS} "
            "flags recorded across the traces)"
        )

    # Recurrence: one problem seen eight times is not eight problems. Rows
    # arrive ordered by distinct flagged days, so the head is the answer.
    recurring = [
        row for row in quality.recurrence if row.anomaly_days >= _MIN_RECURRENCE_DAYS
    ]
    if recurring:
        worst = recurring[0]
        observations.append(
            f"{worst.service} is the most recurrent source on record — flagged "
            f"on {worst.anomaly_days} separate days between {worst.first_seen} "
            f"and {worst.last_seen}, opening {worst.cards_opened} card(s) with "
            f"{worst.folded_repeats} repeat(s) folded in."
        )
        # A rate may only be extrapolated from a span long enough to be one:
        # four flags inside four days is a burst, not a per-fortnight rate.
        # The most-flagged service that clears BOTH bars gets the projection,
        # and the statement names it, so it is never confused with the line
        # above when they differ.
        for row in recurring:
            span = _span_days(row.first_seen, row.last_seen)
            if span is None or span < _MIN_RECURRENCE_SPAN_DAYS:
                continue
            expected = row.anomaly_days / span * _RECURRENCE_HORIZON_DAYS
            predictions.append(
                InsightPrediction(
                    horizon=f"next {_RECURRENCE_HORIZON_DAYS} days",
                    statement=(
                        f"{row.service} flags on ≈{expected:.1f} more day(s) "
                        "if its observed rate simply continues"
                    ),
                    basis=(
                        f"{row.anomaly_days} flagged days across the "
                        f"{span}-day span {row.first_seen} → {row.last_seen}, "
                        "extrapolated flat — a rate, not a cause"
                    ),
                )
            )
            break
    else:
        seen = max((row.anomaly_days for row in quality.recurrence), default=0)
        gaps.append(
            f"recurrence (the most-flagged service has {seen} of "
            f"{_MIN_RECURRENCE_DAYS} distinct flagged days)"
        )

    # The backlog read against measured behaviour: how long a card that is
    # sitting there now has historically waited. Stated per card, because
    # the record says nothing about whether operators work them in series.
    pending = conn.execute(
        "SELECT COUNT(*) AS c FROM actions WHERE state = 'proposed'"
    ).fetchone()["c"]
    if pending and measured >= _MIN_DECISIONS and median_hours is not None:
        predictions.append(
            InsightPrediction(
                horizon="current backlog",
                statement=(
                    f"a pending card settles ≈{median_hours:.2f}h after it was "
                    f"filed — {pending} card(s) are waiting now"
                ),
                basis=(
                    "median of the measured filed→verdict intervals on the "
                    "append-only trail"
                ),
            )
        )

    # --- the rules the system has drafted about itself ----------------------
    drafts, contested = propose_reflex_rules(conn)
    if drafts or contested:
        observations.append(
            f"{len(drafts)} reflex rule draft(s) mined from settled anomaly "
            f"signatures; {contested} signature(s) stayed contested and "
            "produced no draft."
        )
    else:
        gaps.append(
            "reflex drafts (no anomaly signature has settled into a draft yet)"
        )

    # --- audit chain: whether the record above can be trusted at all --------
    audit = ledger.verify(conn)
    if not audit.entries:
        gaps.append("ledger integrity (nothing sealed into the chain yet)")
    elif audit.ok or audit.first_break is None:
        observations.append(
            f"The decision ledger verifies: {audit.verified} of {audit.entries} "
            f"sealed entries re-hash clean against the live rows (head "
            f"{audit.head[:12]}…), with {audit.unsealed_total} row(s) outside "
            "the chain because they never passed the desk."
        )
    else:
        broken = audit.first_break
        observations.append(
            f"The decision ledger DOES NOT verify — {audit.verified} of "
            f"{audit.entries} entries re-hashed clean, then entry "
            f"{broken.ledger_id} ({broken.stream} row {broken.ref_id}) failed "
            f"as {broken.reason}."
        )
        recommendations.append(
            InsightRecommendation(
                focus="audit",
                action=(
                    "Explain the audit-chain break before trusting any figure "
                    "in this report — the history it reads may have been edited."
                ),
                evidence=f"GET /audit/verify: {broken.detail}",
            )
        )

    # --- improvement recommendations mined from behaviour ------------------
    for suggestion in suggest_reflex_rules(conn):
        recommendations.append(
            InsightRecommendation(
                focus=suggestion["service"],
                action="Adopt a pre-approved reflex playbook for this pattern.",
                evidence=(
                    f"{suggestion['approvals']} approvals, 0 rejections in "
                    f"{suggestion['window_days']} days."
                ),
            )
        )
    rejected_rows = conn.execute(
        "SELECT service, COUNT(*) AS rejections FROM decisions "
        "WHERE verdict = 'rejected' GROUP BY service "
        "HAVING rejections > 0 ORDER BY rejections DESC, service"
    ).fetchall()
    for reject_row in rejected_rows:
        recommendations.append(
            InsightRecommendation(
                focus=reject_row["service"],
                action="Review this service's detection threshold or option quality.",
                evidence=f"{reject_row['rejections']} operator rejections recorded.",
            )
        )

    # Each draft is already an actionable proposal with its own evidence, so
    # it is forwarded as one — keyed to the signature it was mined from,
    # which is finer than the per-service suggestion above.
    for draft in drafts:
        signature = draft["signature"]
        recommendations.append(
            InsightRecommendation(
                focus=(
                    f"reflex:{signature['service']}/{signature['severity']}/"
                    f"{signature['direction']}"
                ),
                action=(
                    f"Adopt or amend the drafted reflex rule — {draft['condition']}."
                ),
                evidence=(
                    f"approved {draft['approvals']}× on decision(s) "
                    f"{draft['decision_ids']} in {draft['window_days']} days, "
                    f"never rejected, always {draft['stance']}."
                ),
            )
        )

    # The advice the system gives about its own advice: a playbook whose cards
    # operators keep rejecting is a playbook worth rewriting, and the corpus
    # now knows which one that is.
    runbooks = runbook_effectiveness(conn)
    for record in runbooks.scores:
        if record.adjustment < 0:
            recommendations.append(
                InsightRecommendation(
                    focus=f"runbook:{record.runbook_id}",
                    action=(
                        f"Rewrite or retire the '{record.title}' runbook — the "
                        "cards it matches are usually rejected."
                    ),
                    evidence=record.basis,
                )
            )
    scored = [score for score in runbooks.scores if score.approval_rate is not None]
    if scored:
        leader = max(scored, key=lambda score: (score.approval_rate, score.decided))
        observations.append(
            f"{len(scored)} of {len(runbooks.scores)} runbooks clear the "
            f"{runbooks.min_observations}-decided-card bar for a hit rate; "
            f"'{leader.title}' leads at {round(100 * leader.approval_rate, 1)}% "
            f"({leader.approved} approved of {leader.decided})."
        )
    else:
        gaps.append(
            f"runbook effectiveness (no runbook has reached "
            f"{runbooks.min_observations} decided cards)"
        )

    # Said out loud, last, in the same list the operator is reading: the
    # reads that exist but have not earned a sentence yet.
    if gaps:
        observations.append(
            "Not enough history yet to speak about " + "; ".join(gaps) + "."
        )

    return InsightsReport(
        decisions_considered=total,
        cost_days=cost_days,
        observations=observations,
        predictions=predictions,
        recommendations=recommendations,
        evidence_gaps=gaps,
        note=(
            "Deterministic synthesis over persisted history — figures are "
            "computed, not generated, and every recommendation is a suggestion "
            "for a human (nothing is applied automatically). Reads that have "
            "not cleared their evidence bar are listed in evidence_gaps "
            "instead of being asserted, and no line claims a cause the rows "
            "cannot show."
        ),
    )


class SelfReviewProposal(BaseModel):
    area: str
    proposal: str
    rationale: str
    requires_human: bool = True


class SelfReviewReport(BaseModel):
    cycle: str
    proposals_considered: int
    proposals: list[SelfReviewProposal]
    applied: list[str]
    note: str


@router.post("/self-review")
def self_review(conn: sqlite3.Connection = Depends(db.get_db)) -> SelfReviewReport:
    """Run one self-improvement cycle over the system's own history.

    The system reviews its behaviour and proposes changes to itself — reflex
    candidates, threshold reviews, calibration, backlog hygiene. Nothing is
    applied automatically: the learning loop stays HITL-sacred, so `applied`
    is always empty and every proposal is a human decision. The cycle is
    published to the agent feed so the self-improving loop stays visible.
    """
    report = compute_self_review(conn)
    with db.writing(conn):
        bus.emit(
            conn,
            "self-review",
            "review",
            f"self-review cycle — {report.proposals_considered} improvement "
            "proposal(s) for human review, nothing applied",
        )
    return report


def compute_self_review(conn: sqlite3.Connection) -> SelfReviewReport:
    """One self-review cycle — proposes, never applies."""
    proposals: list[SelfReviewProposal] = []

    # Reflex-rule candidates: patterns operators have always approved.
    for suggestion in suggest_reflex_rules(conn):
        proposals.append(
            SelfReviewProposal(
                area="reflex",
                proposal=f"Adopt a reflex rule for {suggestion['service']}.",
                rationale=(
                    f"{suggestion['approvals']} approvals, 0 rejections in "
                    f"{suggestion['window_days']} days."
                ),
            )
        )

    # Repeatedly-rejected services: thresholds or options need work.
    rejected = conn.execute(
        "SELECT service, COUNT(*) AS rejections FROM decisions "
        "WHERE verdict = 'rejected' GROUP BY service HAVING rejections >= 2 "
        "ORDER BY rejections DESC, service"
    ).fetchall()
    for row in rejected:
        proposals.append(
            SelfReviewProposal(
                area="detection",
                proposal=f"Review {row['service']}'s detection threshold or options.",
                rationale=f"{row['rejections']} operator rejections recorded.",
            )
        )

    # Approval-rate calibration.
    tally = conn.execute(
        "SELECT COUNT(*) AS total, "
        "SUM(CASE WHEN verdict = 'approved' THEN 1 ELSE 0 END) AS approved "
        "FROM decisions"
    ).fetchone()
    total = tally["total"] or 0
    approved = tally["approved"] or 0
    if total >= 5:
        rate = round(100 * approved / total, 1)
        if rate >= 90:
            proposals.append(
                SelfReviewProposal(
                    area="calibration",
                    proposal="Consider raising the escalation bar.",
                    rationale=f"{rate}% of {total} decisions approved — debate may be rare.",
                )
            )
        elif rate <= 30:
            proposals.append(
                SelfReviewProposal(
                    area="calibration",
                    proposal="Review recommendation quality.",
                    rationale=f"only {rate}% of {total} decisions approved — options weak.",
                )
            )

    # Backlog hygiene: proposals waiting on a human.
    pending = conn.execute(
        "SELECT COUNT(*) AS c FROM actions WHERE state = 'proposed'"
    ).fetchone()["c"]
    if pending:
        proposals.append(
            SelfReviewProposal(
                area="backlog",
                proposal=f"Clear {pending} pending proposal(s) from the inbox.",
                rationale="Unreviewed proposals time out unanswered.",
            )
        )

    return SelfReviewReport(
        cycle="self-review",
        proposals_considered=len(proposals),
        proposals=proposals,
        applied=[],
        note=(
            "Self-review proposes; it never applies. Every change is a human "
            "decision — the learning loop stays HITL-sacred."
        ),
    )
